// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKhtyalYRemv8AgcnVDTpvswcjdX0QdXI',
    appId: '1:248111893990:web:30da7bf0515fdc22a2da27',
    messagingSenderId: '248111893990',
    projectId: 'miniproject-6e600',
    authDomain: 'miniproject-6e600.firebaseapp.com',
    storageBucket: 'miniproject-6e600.appspot.com',
    measurementId: 'G-E7RKRNPH3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiva9LZSUpWgrGG6HSorEeVi7bqLj24s',
    appId: '1:248111893990:android:6b5c8e3131a4e250a2da27',
    messagingSenderId: '248111893990',
    projectId: 'miniproject-6e600',
    storageBucket: 'miniproject-6e600.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM8QlNayL3M31OYV5WRuVDWAhFeEk3aVI',
    appId: '1:248111893990:ios:a3a404ff81d9413ea2da27',
    messagingSenderId: '248111893990',
    projectId: 'miniproject-6e600',
    storageBucket: 'miniproject-6e600.appspot.com',
    iosBundleId: 'com.example.notesavingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM8QlNayL3M31OYV5WRuVDWAhFeEk3aVI',
    appId: '1:248111893990:ios:0f737fde1903070da2da27',
    messagingSenderId: '248111893990',
    projectId: 'miniproject-6e600',
    storageBucket: 'miniproject-6e600.appspot.com',
    iosBundleId: 'com.example.notesavingapp.RunnerTests',
  );
}
